// Données des formations Evolutia — alignées sur le calendrier CDG 971 (MAJ 15/07/2026).
// Épreuves et conditions : source officielle concours-territorial.fr et décrets (Légifrance).

export type Epreuve = { type: string; label: string; desc: string };
export type Condition = { voie: string; condition: string };
export type DateCle = { label: string; date: string; statut: "ouvert" | "bientot" | "ferme" };
export type Faq = { q: string; a: string };

export type Formation = {
  titre: string;
  sousTitre: string;
  categorie: string;
  filiere: string;
  type: string;
  descCourte: string;
  seoTitle: string;
  seoDesc: string;
  accroche: string;
  epreuves: Epreuve[];
  programme: string[];
  conditions: Condition[];
  duree: string;
  format: string;
  tauxReussite: string;
  color: string;
  accent: string;
  datesCles: DateCle[];
  faq: Faq[];
  sourceOfficielle: string;
};

export const FILIERES_ORDER = [
  "Filière administrative",
  "Filière animation",
  "Filière médico-sociale",
  "Filière technique",
  "Toutes filières",
];

export const FORMATIONS: Record<string, Formation> = {

  /* ─────────────────────── FILIÈRE ADMINISTRATIVE ─────────────────────── */

  "attache-territorial-guadeloupe": {
    titre: "Attaché Territorial",
    sousTitre: "Concours externe, interne et 3e voie",
    categorie: "Catégorie A",
    filiere: "Filière administrative",
    type: "Concours",
    descCourte: "Le concours administratif de référence en catégorie A : composition, note de spécialité et entretien.",
    seoTitle: "Préparation Concours Attaché Territorial Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez le concours d'attaché territorial en Guadeloupe : composition, note, entretien jury. Formateurs experts, financement CPF. Evolutia, Les Abymes.",
    accroche: "Le concours d'attaché territorial ouvre l'accès aux fonctions de direction administrative des collectivités : direction de services, gestion RH, finances, urbanisme. C'est le concours le plus prestigieux de la filière administrative. Notre préparation couvre les cinq spécialités et les trois voies d'accès.",
    epreuves: [
      { type: "Écrit", label: "Composition sur un sujet d'ordre général (4h, coef. 3)", desc: "Sujet relatif à la place et au rôle des collectivités territoriales dans les problématiques locales (société, économie, éducation, santé, aménagement…). Voie externe uniquement." },
      { type: "Écrit", label: "Note ou rapport de spécialité (4h, coef. 4)", desc: "Rédaction à partir d'un dossier dans la spécialité choisie à l'inscription : administration générale, gestion du secteur sanitaire et social, analyste, animation, urbanisme et développement des territoires. En interne et 3e voie, le rapport doit dégager des solutions opérationnelles." },
      { type: "Oral", label: "Entretien avec le jury (25 min, coef. 4 à 5)", desc: "Présentation du parcours puis échange, le cas échéant sous forme de mise en situation professionnelle, sur les connaissances administratives, la motivation et l'aptitude à exercer. Épreuve facultative de langue vivante possible (15 min, coef. 1)." },
    ],
    programme: [
      "Méthodologie de la composition générale et de la note de spécialité — entraînements corrigés",
      "Culture territoriale : institutions, droit public, finances locales, actualité de la FPT",
      "Approfondissement de la spécialité choisie (administration générale, sanitaire et social…)",
      "Enjeux des collectivités de Guadeloupe : intercommunalité, développement, transition écologique",
      "Simulations d'entretien jury filmées avec débriefing individuel",
      "Veille sur le calendrier et les notes de cadrage officielles",
    ],
    conditions: [
      { voie: "Externe", condition: "Diplôme de niveau 6 (Bac+3, licence) ou qualification reconnue équivalente" },
      { voie: "Interne", condition: "Fonctionnaires et agents publics comptant au moins 4 ans de services publics au 1er janvier de l'année du concours" },
      { voie: "3e voie", condition: "4 ans au moins d'activités professionnelles, de mandats d'élu local ou de responsabilités associatives" },
    ],
    duree: "120 à 180 heures",
    format: "Présentiel (Grand-Camp, Les Abymes) + distanciel",
    tauxReussite: "85%",
    color: "#1B3A6B",
    accent: "#4BADD4",
    datesCles: [
      { label: "Épreuves écrites (session 2026)", date: "19 novembre 2026", statut: "bientot" },
      { label: "Inscriptions (session 2026)", date: "Clôturées le 15 avril 2026", statut: "ferme" },
      { label: "Préparation à l'oral d'admission", date: "Dès les résultats d'admissibilité", statut: "ouvert" },
    ],
    faq: [
      { q: "Quelles sont les spécialités du concours d'attaché territorial ?", a: "Cinq spécialités au choix à l'inscription : administration générale, gestion du secteur sanitaire et social, analyste, animation, urbanisme et développement des territoires. En Guadeloupe, l'administration générale offre le plus de débouchés, mais la spécialité sanitaire et sociale est très recherchée par le Département." },
      { q: "Peut-on encore se préparer pour la session 2026 ?", a: "Les inscriptions 2026 sont closes, mais les candidats inscrits passent les écrits le 19 novembre 2026 : c'est le moment d'intensifier la préparation aux épreuves écrites, puis de préparer l'oral d'admission. Pour les autres candidats, nous préparons dès maintenant la prochaine session." },
      { q: "Quelle différence entre le concours d'attaché et l'examen d'attaché principal ?", a: "Le concours d'attaché permet d'entrer dans le cadre d'emplois (recrutement). L'examen professionnel d'attaché principal est un avancement de grade réservé aux attachés déjà en poste. Evolutia prépare les deux — voir notre formation dédiée à l'examen d'attaché principal." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=275",
  },

  "attache-principal-guadeloupe": {
    titre: "Attaché Principal",
    sousTitre: "Examen professionnel d'avancement de grade",
    categorie: "Catégorie A",
    filiere: "Filière administrative",
    type: "Examen pro.",
    descCourte: "Avancement de grade des attachés : note de mise en situation professionnelle (4h) et entretien jury.",
    seoTitle: "Examen Professionnel Attaché Principal Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez l'examen professionnel d'attaché principal en Guadeloupe : note de 4h, entretien jury. Inscriptions nov.-déc. 2026, épreuves avril 2027. CPF.",
    accroche: "L'examen professionnel d'attaché principal permet aux attachés territoriaux d'accéder au grade supérieur et aux fonctions d'encadrement renforcé. L'écrit de mise en situation professionnelle et l'entretien exigent une préparation ciblée sur la posture de cadre confirmé.",
    epreuves: [
      { type: "Écrit", label: "Note à partir d'un dossier de mise en situation professionnelle (4h, coef. 1)", desc: "Vérifie les capacités d'analyse et l'aptitude à proposer des solutions opérationnelles argumentées. Toute note inférieure à 5/20 est éliminatoire." },
      { type: "Oral", label: "Entretien avec le jury (20 min dont 5 min d'exposé, coef. 1)", desc: "Exposé sur l'expérience professionnelle puis questions sur les aptitudes, notamment en matière d'encadrement, les connaissances administratives générales et la motivation à exercer les fonctions d'attaché principal." },
    ],
    programme: [
      "Méthodologie de la note de mise en situation professionnelle — sujets d'annales corrigés",
      "Actualité des collectivités : finances locales, commande publique, RH, transition écologique",
      "Construction de l'exposé d'expérience professionnelle (5 minutes percutantes)",
      "Posture managériale : encadrement, conduite de projet, relations aux élus",
      "Simulations d'entretien filmées avec débriefing individuel",
      "Planning de révision personnalisé jusqu'aux épreuves d'avril 2027",
    ],
    conditions: [
      { voie: "Avancement de grade", condition: "Attachés justifiant de 3 ans de services effectifs en catégorie A et ayant atteint le 5e échelon du grade d'attaché (possibilité de se présenter 1 an avant de remplir les conditions)" },
    ],
    duree: "50 à 70 heures",
    format: "Présentiel (Grand-Camp, Les Abymes) + distanciel",
    tauxReussite: "85%",
    color: "#F5A623",
    accent: "#1B3A6B",
    datesCles: [
      { label: "Inscriptions", date: "2 nov. → 15 déc. 2026", statut: "bientot" },
      { label: "Épreuve écrite", date: "8 avril 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Dès septembre 2026", statut: "ouvert" },
    ],
    faq: [
      { q: "Qui peut se présenter à l'examen d'attaché principal ?", a: "Les attachés territoriaux justifiant de 3 ans de services effectifs dans un cadre d'emplois de catégorie A et ayant atteint le 5e échelon du grade d'attaché. Vous pouvez vous présenter au plus tôt un an avant de remplir ces conditions — vérifiez votre situation avec votre service RH ou avec nous." },
      { q: "La réussite à l'examen garantit-elle la promotion ?", a: "Non. La réussite vous rend inscriptible au tableau d'avancement, mais la nomination reste une décision de votre collectivité. Un bon dossier et un entretien réussi renforcent toutefois nettement votre position." },
      { q: "Combien de temps de préparation prévoir ?", a: "Comptez 3 à 5 mois. L'écrit de 4h exige un entraînement méthodologique régulier, et l'exposé d'expérience de 5 minutes doit être construit et répété. Nos candidats commencent idéalement en septembre pour des épreuves en avril." },
    ],
    sourceOfficielle: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000844123/",
  },

  "redacteur-territorial-guadeloupe": {
    titre: "Rédacteur Territorial",
    sousTitre: "Concours externe, interne et 3e voie — Rédacteur et Rédacteur principal de 2e classe",
    categorie: "Catégorie B",
    filiere: "Filière administrative",
    type: "Concours",
    descCourte: "Questions et note sur dossier (3h chacune), entretien jury. Session 2027 : inscriptions février-mars 2027.",
    seoTitle: "Préparation Concours Rédacteur Territorial Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez le concours de rédacteur territorial en Guadeloupe : questions, note sur dossier, entretien. Session 2027, financement CPF. Evolutia, Les Abymes.",
    accroche: "Le concours de rédacteur territorial (catégorie B) est la porte d'entrée des missions administratives qualifiées : instruction de dossiers, rédaction d'actes, comptabilité, gestion. Les concours de rédacteur et de rédacteur principal de 2e classe sont organisés aux mêmes dates en 2027 — notre préparation couvre les deux.",
    epreuves: [
      { type: "Écrit", label: "Réponses à une série de questions (3h, coef. 1)", desc: "Voie externe rédacteur : questions portant sur le domaine choisi à l'inscription. Pour le concours de rédacteur principal de 2e classe : questions de droit public et de finances publiques portant sur le fonctionnement des collectivités." },
      { type: "Écrit", label: "Note ou rapport à partir d'un dossier (3h, coef. 1)", desc: "Rédaction d'une note sur les missions, compétences et moyens d'action des collectivités territoriales. En voie interne et 3e voie, c'est l'épreuve écrite unique. Pour rédacteur principal : rapport assorti de propositions opérationnelles." },
      { type: "Oral", label: "Entretien avec le jury (20 min, coef. 1)", desc: "Exposé du candidat sur sa formation et son projet professionnel (externe) ou sur les acquis de son expérience (interne, 3e voie), puis échange sur la motivation et l'aptitude à exercer les missions du cadre d'emplois." },
    ],
    programme: [
      "Droit public, finances publiques et fonctionnement des collectivités territoriales",
      "Méthodologie de la note sur dossier et des réponses à questions — approche note de cadrage",
      "Actualité territoriale nationale et locale (Guadeloupe, Antilles-Guyane)",
      "Entraînements intensifs sur sujets officiels — corrigés détaillés individuels",
      "Coaching oral : exposé, posture, argumentation, gestion du stress",
      "Suivi personnalisé par formateur référent jusqu'aux épreuves d'octobre 2027",
    ],
    conditions: [
      { voie: "Externe", condition: "Baccalauréat (niveau 4) pour rédacteur ; Bac+2 (niveau 5) pour rédacteur principal de 2e classe" },
      { voie: "Interne", condition: "Fonctionnaires et agents publics comptant au moins 4 ans de services publics au 1er janvier de l'année du concours" },
      { voie: "3e voie", condition: "4 ans au moins d'activités professionnelles, de mandats d'élu local ou de responsabilités associatives" },
    ],
    duree: "80 à 120 heures",
    format: "Présentiel (Grand-Camp, Les Abymes) + distanciel",
    tauxReussite: "85%",
    color: "#1B3A6B",
    accent: "#4BADD4",
    datesCles: [
      { label: "Inscriptions (session 2027)", date: "2 fév. → 10 mars 2027", statut: "bientot" },
      { label: "Épreuves écrites", date: "14 octobre 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Janvier 2027", statut: "ouvert" },
    ],
    faq: [
      { q: "Quelles sont exactement les épreuves écrites du concours de rédacteur ?", a: "En voie externe : une série de questions (3h) et la rédaction d'une note à partir d'un dossier (3h). En voie interne et 3e voie : uniquement la note sur dossier (3h). Contrairement à une idée répandue, il n'y a ni dissertation de culture générale ni note de synthèse classique — la méthodologie attendue est précisée dans les notes de cadrage officielles, sur lesquelles nous nous appuyons." },
      { q: "Rédacteur ou rédacteur principal de 2e classe : quel concours choisir ?", a: "Les deux concours sont organisés aux mêmes dates en 2027. Le concours de rédacteur principal de 2e classe exige un Bac+2 et des épreuves plus techniques (droit public et finances publiques), mais offre un grade et une rémunération supérieurs dès l'entrée. Si vous avez le diplôme requis, il est souvent pertinent de viser le principal." },
      { q: "Combien de temps faut-il pour se préparer ?", a: "Entre 6 et 9 mois de préparation régulière. Les épreuves écrites de 3h demandent un entraînement méthodologique prolongé, et l'actualité territoriale se travaille dans la durée. Pour des épreuves en octobre 2027, commencez idéalement en début d'année 2027." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=324",
  },

  "redacteur-principal-guadeloupe": {
    titre: "Rédacteur Principal",
    sousTitre: "Examens professionnels d'avancement de grade (1re et 2e classe)",
    categorie: "Catégorie B",
    filiere: "Filière administrative",
    type: "Examen pro.",
    descCourte: "Avancement de grade : rapport avec propositions (3h) et entretien jury. Épreuves le 24 septembre 2026.",
    seoTitle: "Examen Professionnel Rédacteur Principal Guadeloupe 2026 | Evolutia",
    seoDesc: "Préparez l'examen professionnel de rédacteur principal 1re ou 2e classe en Guadeloupe : rapport écrit 3h + entretien. Épreuves sept. 2026. CPF possible.",
    accroche: "Les examens professionnels de rédacteur principal (2e classe et 1re classe) permettent aux rédacteurs en poste d'accéder aux grades supérieurs. Contrairement à une idée reçue, l'examen comporte une véritable épreuve écrite : un rapport avec propositions opérationnelles, en plus de l'entretien avec le jury.",
    epreuves: [
      { type: "Écrit", label: "Rapport à partir d'un dossier, assorti de propositions (3h, coef. 1)", desc: "Dossier portant sur les missions, compétences et moyens d'action des collectivités territoriales. Une note inférieure à 5/20 interdit l'accès à l'oral. Épreuve identique pour la 1re et la 2e classe." },
      { type: "Oral", label: "Entretien avec le jury (20 min dont 5 min d'exposé, coef. 1)", desc: "Exposé sur les acquis de l'expérience professionnelle, puis questions permettant d'apprécier les facultés d'analyse, l'aptitude et la motivation à exercer les missions du grade, y compris l'encadrement d'équipe." },
    ],
    programme: [
      "Méthodologie du rapport avec propositions opérationnelles — annales corrigées",
      "Missions, compétences et moyens d'action des collectivités : les fondamentaux à maîtriser",
      "Construction de l'exposé d'expérience professionnelle (5 minutes)",
      "Posture d'encadrement : animer une équipe, organiser un service",
      "Simulations d'entretien jury filmées avec débriefing individuel",
      "Relecture et correction individuelles de vos écrits d'entraînement",
    ],
    conditions: [
      { voie: "2e classe", condition: "Rédacteurs ayant atteint le 6e échelon du grade et justifiant d'au moins 3 ans de services effectifs en catégorie B (conditions applicables aux tableaux d'avancement à compter de 2026)" },
      { voie: "1re classe", condition: "Rédacteurs principaux de 2e classe justifiant d'au moins 1 an dans le 6e échelon et de 3 ans de services effectifs en catégorie B" },
    ],
    duree: "40 à 60 heures",
    format: "Présentiel (Grand-Camp) + accompagnement individuel en distanciel",
    tauxReussite: "88%",
    color: "#F5A623",
    accent: "#1B3A6B",
    datesCles: [
      { label: "Épreuve écrite (session 2026)", date: "24 septembre 2026", statut: "bientot" },
      { label: "Inscriptions (session 2026)", date: "Clôturées — CDG 971", statut: "ferme" },
      { label: "Préparation intensive à l'écrit et à l'oral", date: "Disponible dès maintenant", statut: "ouvert" },
    ],
    faq: [
      { q: "L'examen de rédacteur principal comporte-t-il un écrit ?", a: "Oui. L'examen d'avancement de grade comporte une épreuve écrite de 3h — un rapport à partir d'un dossier, assorti de propositions opérationnelles — puis un entretien de 20 minutes. Une note inférieure à 5/20 à l'écrit est éliminatoire : ne négligez pas cette épreuve." },
      { q: "Quelle est la différence entre la 1re et la 2e classe ?", a: "Les épreuves sont identiques, mais les conditions d'accès diffèrent : la 2e classe est ouverte aux rédacteurs ayant atteint le 6e échelon avec 3 ans de services en catégorie B ; la 1re classe aux rédacteurs principaux de 2e classe avec 1 an dans le 6e échelon. Le jury attend un niveau de recul et de responsabilité supérieur pour la 1re classe." },
      { q: "Comment se préparer efficacement en travaillant à plein temps ?", a: "L'examen se prépare en 2 à 4 mois avec 3 à 4 heures de travail hebdomadaire : entraînements au rapport corrigés individuellement, construction de l'exposé de 5 minutes et simulations d'entretien. Notre format soirée (15h30-18h30) est conçu pour les agents en poste." },
    ],
    sourceOfficielle: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000026251677",
  },

  "adjoint-administratif-principal-guadeloupe": {
    titre: "Adjoint Administratif Principal de 2e Classe",
    sousTitre: "Examen professionnel d'avancement de grade",
    categorie: "Catégorie C",
    filiere: "Filière administrative",
    type: "Examen pro.",
    descCourte: "Avancement de grade : épreuve écrite professionnelle (1h30) et entretien. Épreuves en mars 2027.",
    seoTitle: "Examen Adjoint Administratif Principal Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez l'examen professionnel d'adjoint administratif principal 2e classe en Guadeloupe : écrit 1h30 + entretien. Inscriptions oct.-nov. 2026. CPF.",
    accroche: "L'examen professionnel d'adjoint administratif principal de 2e classe permet aux adjoints administratifs d'accéder au grade supérieur. Les épreuves sont accessibles mais ne s'improvisent pas : l'écrit teste la compréhension et la retranscription rapides, l'entretien valorise votre parcours.",
    epreuves: [
      { type: "Écrit", label: "Épreuve écrite à caractère professionnel (1h30, coef. 2)", desc: "À partir de documents succincts, trois à cinq questions appelant des réponses brèves ou sous forme de tableaux, vérifiant les capacités de compréhension et l'aptitude à retranscrire les idées principales. Note minimale de 5/20 pour accéder à l'oral." },
      { type: "Oral", label: "Entretien avec le jury (15 min dont 5 min de présentation, coef. 3)", desc: "Présentation de l'expérience professionnelle sur la base d'un document retraçant le parcours, puis conversation avec le jury sur la motivation et l'aptitude à exercer les missions confiées." },
    ],
    programme: [
      "Entraînement à l'épreuve écrite : lecture rapide, réponses brèves, tableaux",
      "Vocabulaire administratif et fonctionnement des collectivités territoriales",
      "Rédaction du document de parcours professionnel",
      "Construction de la présentation orale de 5 minutes",
      "Simulations d'entretien avec jury fictif et débriefing",
      "Séances adaptées aux agents en poste (fin de journée)",
    ],
    conditions: [
      { voie: "Avancement de grade", condition: "Adjoints administratifs ayant atteint le 4e échelon et comptant au moins 3 ans de services effectifs dans le grade ou un grade équivalent (échelle C1)" },
    ],
    duree: "30 à 50 heures",
    format: "Présentiel (Grand-Camp, Les Abymes)",
    tauxReussite: "85%",
    color: "#4BADD4",
    accent: "#1B3A6B",
    datesCles: [
      { label: "Inscriptions", date: "20 oct. → 25 nov. 2026", statut: "bientot" },
      { label: "Épreuve écrite", date: "18 mars 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Novembre 2026", statut: "ouvert" },
    ],
    faq: [
      { q: "Qui peut passer l'examen d'adjoint administratif principal de 2e classe ?", a: "Les adjoints administratifs territoriaux ayant atteint le 4e échelon et comptant au moins 3 ans de services effectifs dans le grade. Vous pouvez vous présenter au plus tôt un an avant de remplir ces conditions." },
      { q: "En quoi consiste l'épreuve écrite ?", a: "C'est une épreuve courte (1h30) mais exigeante : à partir de documents succincts, vous répondez à 3 à 5 questions par des réponses brèves ou des tableaux. Elle teste la rapidité de compréhension et la capacité à retranscrire les idées essentielles — cela s'entraîne avec des sujets types." },
      { q: "L'oral compte-t-il plus que l'écrit ?", a: "Oui : l'entretien est affecté du coefficient 3 contre 2 pour l'écrit. Une présentation de parcours bien construite et des réponses posées font souvent la différence. Nous consacrons la moitié de la préparation aux simulations d'entretien." },
    ],
    sourceOfficielle: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000466090",
  },

  /* ─────────────────────── FILIÈRE ANIMATION ─────────────────────── */

  "animateur-territorial-guadeloupe": {
    titre: "Animateur Territorial",
    sousTitre: "Concours — Animateur et Animateur principal de 2e classe",
    categorie: "Catégorie B",
    filiere: "Filière animation",
    type: "Concours",
    descCourte: "Questions ou rapport sur dossier animation (3h) et entretien. Session 2027 : épreuves en septembre.",
    seoTitle: "Préparation Concours Animateur Territorial Guadeloupe 2027 | Evolutia",
    seoDesc: "Préparez le concours d'animateur territorial en Guadeloupe : épreuves sur dossier animation, entretien jury. Inscriptions mars-avril 2027. CPF possible.",
    accroche: "L'animateur territorial (catégorie B) coordonne les activités d'animation sociale, socio-éducative ou culturelle des collectivités : centres de loisirs, politique jeunesse, animation périscolaire. Les concours d'animateur et d'animateur principal de 2e classe sont organisés aux mêmes dates en 2027.",
    epreuves: [
      { type: "Écrit", label: "Animateur — Questions à partir d'un dossier (3h, coef. 1)", desc: "3 à 5 questions à partir d'un dossier portant sur l'animation sociale, socio-éducative ou culturelle dans les collectivités (voie externe). En interne et 3e voie : rédaction d'une note à partir d'un dossier (3h)." },
      { type: "Écrit", label: "Animateur principal 2e cl. — Rapport avec propositions (3h, coef. 1)", desc: "Rédaction d'un rapport à partir d'un dossier sur l'animation, assorti de propositions opérationnelles. En interne et 3e voie s'y ajoutent des questions sur l'animation (3h)." },
      { type: "Oral", label: "Entretien avec le jury (20 min dont 5 min d'exposé, coef. 1)", desc: "Exposé sur la formation et le projet professionnel (externe) ou sur les acquis de l'expérience (interne, 3e voie), puis échange sur la motivation, l'aptitude aux missions et, pour le grade principal, l'aptitude à l'encadrement." },
    ],
    programme: [
      "Politiques d'animation des collectivités : jeunesse, périscolaire, vie sociale et culturelle",
      "Méthodologie des questions sur dossier, de la note et du rapport avec propositions",
      "Cadre réglementaire : accueils collectifs de mineurs, sécurité, responsabilité",
      "Entraînements écrits corrigés individuellement sur sujets officiels",
      "Simulations d'entretien jury adaptées au grade visé",
      "Focus Guadeloupe : dispositifs locaux, acteurs, enjeux du territoire",
    ],
    conditions: [
      { voie: "Externe", condition: "Diplôme professionnel de niveau 4 du domaine de l'animation (animateur) ou de niveau 5 (animateur principal de 2e classe)" },
      { voie: "Interne", condition: "Fonctionnaires et agents publics comptant au moins 4 ans de services publics ; voie interne spéciale pour les ATSEM justifiant de 4 ans de services (animateur)" },
      { voie: "3e voie", condition: "4 ans au moins d'activités professionnelles, de mandats d'élu local ou de responsabilités associatives" },
    ],
    duree: "80 à 120 heures",
    format: "Présentiel (Grand-Camp, Les Abymes) + distanciel",
    tauxReussite: "85%",
    color: "#4BADD4",
    accent: "#F5A623",
    datesCles: [
      { label: "Inscriptions (session 2027)", date: "2 mars → 7 avril 2027", statut: "bientot" },
      { label: "Épreuves écrites", date: "23 septembre 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Début 2027", statut: "ouvert" },
    ],
    faq: [
      { q: "Quel diplôme faut-il pour le concours d'animateur territorial ?", a: "En voie externe, un diplôme professionnel de l'animation de niveau 4 (BPJEPS notamment) pour le concours d'animateur, ou de niveau 5 (DEJEPS…) pour animateur principal de 2e classe. La voie interne est ouverte sans condition de diplôme aux agents publics avec 4 ans de services, dont une voie spéciale pour les ATSEM." },
      { q: "Le BAFA suffit-il pour se présenter ?", a: "Non, le BAFA n'est pas un diplôme professionnel : il ne permet pas l'accès au concours externe. Il faut un BPJEPS ou équivalent (niveau 4). En revanche, une expérience d'animation avec BAFA peut ouvrir la 3e voie si vous justifiez de 4 ans d'activité." },
      { q: "Quels débouchés en Guadeloupe ?", a: "Les communes et intercommunalités recrutent des animateurs pour les accueils périscolaires, les centres de loisirs, les projets éducatifs de territoire et l'animation sociale. Le grade d'animateur principal ouvre vers la coordination d'équipes et la direction de structures." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=367",
  },

  "adjoint-animation-principal-guadeloupe": {
    titre: "Adjoint d'Animation Principal de 2e Classe",
    sousTitre: "Concours externe, interne et 3e voie",
    categorie: "Catégorie C",
    filiere: "Filière animation",
    type: "Concours",
    descCourte: "QCM et entretien (externe), note et cas pratique selon la voie. Épreuves le 25 mars 2027.",
    seoTitle: "Concours Adjoint d'Animation Principal Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez le concours d'adjoint d'animation principal 2e classe en Guadeloupe : QCM, note, entretien. Inscriptions sept.-nov. 2026, épreuves mars 2027.",
    accroche: "Le concours d'adjoint d'animation principal de 2e classe (catégorie C) est la première marche des métiers de l'animation territoriale : activités périscolaires, centres de loisirs, animation de quartier. Les épreuves varient fortement selon la voie d'accès — notre préparation est ciblée sur la vôtre.",
    epreuves: [
      { type: "Écrit", label: "Externe — QCM (45 min, coef. 1)", desc: "Questionnaire à choix multiples sur des notions élémentaires d'organisation des collectivités locales et de consignes d'hygiène et de sécurité." },
      { type: "Écrit", label: "Interne — QCM (45 min, coef. 3) + note (2h, coef. 2)", desc: "QCM sur l'accueil, la compréhension du public, la protection et les droits de l'enfant, puis rédaction d'une note à partir d'un texte ou article de presse relatif à l'animation. En 3e voie : questions sur les collectivités (45 min) et cas pratique (1h30)." },
      { type: "Oral", label: "Entretien avec le jury (15 à 20 min, coef. 2 à 4)", desc: "En externe : entretien de motivation de 15 minutes. En interne : entretien de 20 minutes après 20 minutes de préparation à partir d'une question, d'un texte ou d'un document. En 3e voie : exposé sur l'expérience puis échange." },
    ],
    programme: [
      "Organisation et fonctionnement des collectivités locales — l'essentiel pour le QCM",
      "Hygiène, sécurité, protection et droits de l'enfant",
      "Méthodologie de la note et du cas pratique selon la voie d'accès",
      "Entraînements QCM chronométrés en conditions réelles",
      "Simulations d'entretien de motivation avec débriefing",
      "Connaissance du secteur de l'animation en Guadeloupe",
    ],
    conditions: [
      { voie: "Externe", condition: "Diplôme professionnel de niveau 3 (CAP/BEP) du domaine de l'animation ou qualification équivalente" },
      { voie: "Interne", condition: "Fonctionnaires et agents publics — conditions de services précisées par l'organisateur" },
      { voie: "3e voie", condition: "4 ans au moins d'activités professionnelles, de mandats d'élu local ou de responsabilités associatives" },
    ],
    duree: "50 à 70 heures",
    format: "Présentiel (Grand-Camp, Les Abymes)",
    tauxReussite: "85%",
    color: "#F5A623",
    accent: "#4BADD4",
    datesCles: [
      { label: "Inscriptions", date: "29 sept. → 4 nov. 2026", statut: "bientot" },
      { label: "Épreuves", date: "25 mars 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Octobre 2026", statut: "ouvert" },
    ],
    faq: [
      { q: "Le CAP AEPE ou le CPJEPS permettent-ils de se présenter ?", a: "Oui, le concours externe est ouvert aux titulaires d'un diplôme professionnel de niveau 3 délivré dans les domaines correspondant aux missions du cadre d'emplois — le CPJEPS ou le CAP AEPE en font partie. Une qualification reconnue équivalente peut aussi être acceptée." },
      { q: "Comment se préparer au QCM ?", a: "Le QCM de 45 minutes porte sur des notions précises : organisation des collectivités, hygiène et sécurité, et en interne les droits de l'enfant. La clé est l'entraînement répété sur des QCM types chronométrés — c'est le cœur de notre préparation écrite." },
      { q: "Quelle voie choisir si je travaille déjà dans l'animation ?", a: "Si vous êtes déjà agent public, la voie interne valorise vos connaissances professionnelles. Si vous travaillez dans l'animation associative ou privée depuis 4 ans ou plus, la 3e voie est adaptée. Nous validons votre éligibilité lors de l'entretien d'orientation gratuit." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=369",
  },

  /* ─────────────────────── FILIÈRE MÉDICO-SOCIALE ─────────────────────── */

  "sage-femme-guadeloupe": {
    titre: "Sage-Femme Territoriale",
    sousTitre: "Concours sur titres avec épreuve",
    categorie: "Catégorie A",
    filiere: "Filière médico-sociale",
    type: "Concours",
    descCourte: "Concours sur titres : entretien de 25 minutes avec le jury. Épreuve le 22 mars 2027.",
    seoTitle: "Concours Sage-Femme Territoriale Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez le concours de sage-femme territoriale en Guadeloupe : entretien jury de 25 min. Inscriptions sept.-nov. 2026, épreuve mars 2027. PMI, CDG 971.",
    accroche: "Le concours de sage-femme territoriale ouvre les portes des services de PMI (protection maternelle et infantile) du Département et des centres de santé des collectivités. C'est un concours sur titres : tout se joue sur un entretien de 25 minutes, qui se prépare sérieusement.",
    epreuves: [
      { type: "Oral", label: "Entretien avec le jury (25 min dont 10 min d'exposé, coef. 1)", desc: "Exposé du candidat sur sa formation et son projet professionnel, puis échange permettant d'apprécier la capacité à s'intégrer dans l'environnement territorial, la motivation et l'aptitude à exercer les missions du cadre d'emplois. Une fiche individuelle de renseignement est transmise à l'inscription (non notée)." },
    ],
    programme: [
      "Environnement territorial : Département, PMI, politiques de santé publique locales",
      "Construction de l'exposé de 10 minutes : parcours, projet, motivation",
      "Enjeux de santé maternelle et infantile en Guadeloupe",
      "Questions types du jury et posture professionnelle",
      "Simulations d'entretien filmées avec débriefing individuel",
      "Préparation de la fiche individuelle de renseignement",
    ],
    conditions: [
      { voie: "Sur titres", condition: "Diplôme d'État de sage-femme (ou autorisation d'exercice de la profession en France)" },
    ],
    duree: "20 à 30 heures",
    format: "Présentiel (Grand-Camp) + distanciel",
    tauxReussite: "85%",
    color: "#1B3A6B",
    accent: "#F5A623",
    datesCles: [
      { label: "Inscriptions", date: "29 sept. → 4 nov. 2026", statut: "bientot" },
      { label: "Épreuve d'entretien", date: "22 mars 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Janvier 2027", statut: "ouvert" },
    ],
    faq: [
      { q: "Pourquoi préparer un simple entretien de 25 minutes ?", a: "Parce que tout le concours repose dessus. Le jury évalue en 25 minutes votre connaissance de l'environnement territorial (PMI, Département, politiques de santé), votre projet professionnel et votre posture. Les candidates non préparées échouent souvent sur les questions institutionnelles, pas sur le cœur de métier." },
      { q: "Où exerce une sage-femme territoriale en Guadeloupe ?", a: "Principalement en PMI au sein du Conseil départemental : consultations prénatales et postnatales, planification familiale, visites à domicile, actions de prévention. Des postes existent aussi dans les centres de santé municipaux." },
      { q: "Quelle est la différence avec l'exercice hospitalier ?", a: "La sage-femme territoriale relève de la fonction publique territoriale (et non hospitalière) : missions de prévention et de suivi ambulatoire plutôt que d'accouchement, horaires réguliers, ancrage dans les politiques sociales du territoire." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=352",
  },

  "puericultrice-guadeloupe": {
    titre: "Puéricultrice Territoriale",
    sousTitre: "Concours sur titres avec épreuve — classe normale",
    categorie: "Catégorie A",
    filiere: "Filière médico-sociale",
    type: "Concours",
    descCourte: "Concours sur titres : entretien de 25 minutes avec le jury. Épreuve le 15 février 2027.",
    seoTitle: "Concours Puéricultrice Territoriale Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez le concours de puéricultrice territoriale en Guadeloupe : entretien jury 25 min. Inscriptions sept.-nov. 2026, épreuve février 2027. PMI, crèches.",
    accroche: "La puéricultrice territoriale exerce en PMI, en crèche municipale ou dans les services petite enfance des collectivités. Le concours sur titres repose sur un entretien unique de 25 minutes : votre diplôme vous rend éligible, votre préparation fait la différence.",
    epreuves: [
      { type: "Oral", label: "Entretien avec le jury (25 min dont 5 min d'exposé, coef. 1)", desc: "Exposé sur la formation et le projet professionnel, puis échange permettant d'apprécier la capacité à s'intégrer dans l'environnement professionnel territorial, la motivation et l'aptitude à exercer les missions du cadre d'emplois." },
    ],
    programme: [
      "Environnement territorial : PMI, modes d'accueil, politiques petite enfance",
      "Construction de l'exposé de 5 minutes : parcours, projet, motivation",
      "Enjeux de la petite enfance en Guadeloupe : offre d'accueil, prévention, parentalité",
      "Questions types du jury : direction de crèche, agrément des assistantes maternelles…",
      "Simulations d'entretien filmées avec débriefing individuel",
      "Posture de cadre de catégorie A en collectivité",
    ],
    conditions: [
      { voie: "Sur titres", condition: "Diplôme d'État de puéricultrice (ou autorisation d'exercice pour les ressortissants de l'UE/EEE)" },
    ],
    duree: "20 à 30 heures",
    format: "Présentiel (Grand-Camp) + distanciel",
    tauxReussite: "85%",
    color: "#4BADD4",
    accent: "#1B3A6B",
    datesCles: [
      { label: "Inscriptions", date: "29 sept. → 4 nov. 2026", statut: "bientot" },
      { label: "Épreuve d'entretien", date: "15 février 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Décembre 2026", statut: "ouvert" },
    ],
    faq: [
      { q: "Quels postes pour une puéricultrice territoriale en Guadeloupe ?", a: "Les débouchés principaux : PMI du Conseil départemental (consultations infantiles, agrément et suivi des assistantes maternelles), direction ou direction adjointe de crèche municipale, coordination petite enfance en intercommunalité." },
      { q: "Que demande le jury lors de l'entretien ?", a: "Au-delà de votre parcours, le jury teste votre connaissance du cadre territorial : missions de la PMI, rôle du Département, réglementation des établissements d'accueil du jeune enfant, management d'équipe. C'est là que la préparation est déterminante." },
      { q: "Je suis infirmière puéricultrice à l'hôpital, puis-je candidater ?", a: "Oui, le diplôme d'État de puéricultrice suffit pour vous inscrire au concours sur titres. Le passage du milieu hospitalier vers la territoriale est fréquent — le jury attendra que vous démontriez votre compréhension des missions territoriales (prévention, accueil, protection de l'enfance)." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=354",
  },

  "assistant-socio-educatif-guadeloupe": {
    titre: "Assistant Socio-Éducatif — Classe Exceptionnelle",
    sousTitre: "Examen professionnel d'avancement de grade",
    categorie: "Catégorie A",
    filiere: "Filière médico-sociale",
    type: "Examen pro.",
    descCourte: "Avancement de grade : dossier de parcours professionnel puis entretien de 35 minutes. Épreuves sept. 2027.",
    seoTitle: "Examen Assistant Socio-Éducatif Classe Except. Guadeloupe 2027 | Evolutia",
    seoDesc: "Préparez l'examen d'assistant socio-éducatif de classe exceptionnelle en Guadeloupe : dossier + entretien 35 min. Inscriptions mars-avril 2027. CPF.",
    accroche: "L'examen professionnel d'accès à la classe exceptionnelle permet aux assistants socio-éducatifs (assistants de service social, éducateurs spécialisés, CESF) d'accéder au grade sommital de leur cadre d'emplois. La sélection repose sur un dossier écrit et un entretien approfondi de 35 minutes.",
    epreuves: [
      { type: "Dossier", label: "Examen du dossier du candidat (admissibilité, coef. 1)", desc: "Dossier établi selon le modèle réglementaire : formation et niveau de qualification, parcours professionnel, acquis de l'expérience et motivations, description d'une réalisation professionnelle. Pas d'épreuve en présentiel à ce stade." },
      { type: "Oral", label: "Entretien avec le jury (35 min : 10 min d'exposé + 25 min d'échange, coef. 2)", desc: "Exposé sur les acquis de l'expérience puis échange sur l'expertise technique, l'aptitude à concevoir et mettre en œuvre des politiques sociales, à diriger un service ou coordonner des équipes, et la connaissance de l'action sociale des collectivités." },
    ],
    programme: [
      "Construction du dossier réglementaire : valorisation du parcours et de la réalisation professionnelle",
      "Relectures et corrections individuelles du dossier avant dépôt",
      "Politiques sociales et médico-sociales des collectivités : les fondamentaux à jour",
      "Construction de l'exposé de 10 minutes sur les acquis de l'expérience",
      "Simulations d'entretien de 35 minutes avec jury fictif et débriefing",
      "Posture de cadre expert : coordination, conception de dispositifs, partenariats",
    ],
    conditions: [
      { voie: "Avancement de grade", condition: "Assistants socio-éducatifs justifiant d'au moins 3 ans de services effectifs en catégorie A et d'1 an d'ancienneté dans le 3e échelon du grade (au 31 décembre de l'année du tableau d'avancement)" },
    ],
    duree: "30 à 50 heures",
    format: "Présentiel (Grand-Camp) + accompagnement individuel en distanciel",
    tauxReussite: "85%",
    color: "#1B3A6B",
    accent: "#4BADD4",
    datesCles: [
      { label: "Inscriptions", date: "16 mars → 21 avril 2027", statut: "bientot" },
      { label: "Épreuve d'entretien", date: "16 septembre 2027", statut: "bientot" },
      { label: "Accompagnement dossier", date: "Dès l'ouverture des inscriptions", statut: "ouvert" },
    ],
    faq: [
      { q: "Le dossier est-il vraiment déterminant ?", a: "Oui : c'est l'épreuve d'admissibilité. Le jury sélectionne sur dossier avant même de vous rencontrer. La description de votre réalisation professionnelle doit démontrer un niveau d'expertise et de responsabilité correspondant à la classe exceptionnelle — nous le construisons ensemble, avec plusieurs relectures." },
      { q: "Qui est concerné par cet examen ?", a: "Les assistants socio-éducatifs territoriaux (assistants de service social, éducateurs spécialisés, conseillers en économie sociale et familiale) avec au moins 3 ans de services en catégorie A et 1 an dans le 3e échelon de leur grade." },
      { q: "Comment se déroule l'entretien de 35 minutes ?", a: "Il débute par votre exposé de 10 minutes maximum sur les acquis de votre expérience, suivi de 25 minutes d'échange : expertise technique, capacité à concevoir des dispositifs, à encadrer ou coordonner, connaissance de l'action sociale territoriale. C'est un oral dense qui se prépare par des simulations répétées." },
    ],
    sourceOfficielle: "https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000041751784",
  },

  "educateur-jeunes-enfants-guadeloupe": {
    titre: "Éducateur de Jeunes Enfants — Classe Exceptionnelle",
    sousTitre: "Examen professionnel d'avancement de grade",
    categorie: "Catégorie A",
    filiere: "Filière médico-sociale",
    type: "Examen pro.",
    descCourte: "Avancement de grade : dossier de parcours professionnel puis entretien de 35 minutes. Épreuves fév. 2027.",
    seoTitle: "Examen Éducateur Jeunes Enfants Classe Except. Guadeloupe 2027 | Evolutia",
    seoDesc: "Préparez l'examen d'éducateur de jeunes enfants de classe exceptionnelle en Guadeloupe : dossier + entretien 35 min. Épreuves février 2027. CPF possible.",
    accroche: "L'examen professionnel d'accès à la classe exceptionnelle permet aux éducateurs de jeunes enfants territoriaux d'accéder au grade sommital, tourné vers la direction de structures d'accueil et la coordination d'équipes. Dossier écrit puis entretien de 35 minutes : chaque étape se travaille.",
    epreuves: [
      { type: "Dossier", label: "Examen du dossier du candidat (admissibilité, coef. 1)", desc: "Dossier établi selon le modèle réglementaire : formation et niveau de qualification, parcours professionnel, acquis de l'expérience et motivations, description d'une réalisation professionnelle. Pas d'épreuve en présentiel à ce stade." },
      { type: "Oral", label: "Entretien avec le jury (35 min : 10 min d'exposé + 25 min d'échange, coef. 2)", desc: "Exposé sur les acquis de l'expérience puis échange sur l'expertise technique, l'aptitude à concevoir des politiques liées à l'enfance, à diriger un établissement d'accueil du jeune enfant ou coordonner des équipes, et la connaissance de l'action des collectivités." },
    ],
    programme: [
      "Construction du dossier réglementaire : valorisation du parcours et de la réalisation professionnelle",
      "Relectures et corrections individuelles du dossier avant dépôt",
      "Politiques petite enfance des collectivités : accueil du jeune enfant, parentalité, inclusion",
      "Construction de l'exposé de 10 minutes sur les acquis de l'expérience",
      "Simulations d'entretien de 35 minutes avec jury fictif et débriefing",
      "Posture de direction : gestion d'équipe et pilotage d'une structure d'accueil",
    ],
    conditions: [
      { voie: "Avancement de grade", condition: "Éducateurs de jeunes enfants justifiant d'au moins 3 ans de services effectifs en catégorie A et d'1 an d'ancienneté dans le 3e échelon du grade (au 31 décembre de l'année du tableau d'avancement)" },
    ],
    duree: "30 à 50 heures",
    format: "Présentiel (Grand-Camp) + accompagnement individuel en distanciel",
    tauxReussite: "85%",
    color: "#4BADD4",
    accent: "#F5A623",
    datesCles: [
      { label: "Inscriptions", date: "13 oct. → 18 nov. 2026 (à confirmer CDG 971)", statut: "bientot" },
      { label: "Épreuve d'entretien", date: "11 février 2027", statut: "bientot" },
      { label: "Accompagnement dossier", date: "Dès maintenant", statut: "ouvert" },
    ],
    faq: [
      { q: "Quelle différence entre cet examen et le concours d'EJE ?", a: "Le concours d'éducateur de jeunes enfants permet d'entrer dans la fonction publique territoriale. L'examen de classe exceptionnelle est un avancement de grade réservé aux EJE territoriaux déjà titulaires, avec 3 ans de services en catégorie A et 1 an dans le 3e échelon." },
      { q: "Que doit contenir la description de la réalisation professionnelle ?", a: "Une action significative que vous avez conçue ou pilotée : ouverture ou réorganisation d'une structure, projet pédagogique innovant, démarche d'inclusion… Le jury y cherche la preuve d'un niveau de responsabilité correspondant à la classe exceptionnelle. Nous vous aidons à choisir et à rédiger cette réalisation." },
      { q: "Vers quels postes mène la classe exceptionnelle ?", a: "Principalement la direction de crèches et multi-accueils, la coordination petite enfance à l'échelle d'une commune ou d'une intercommunalité, et le pilotage de projets éducatifs de territoire." },
    ],
    sourceOfficielle: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000041751766",
  },

  "aide-soignant-guadeloupe": {
    titre: "Aide-Soignant Territorial",
    sousTitre: "Concours sur titres avec épreuve — classe normale",
    categorie: "Catégorie B",
    filiere: "Filière médico-sociale",
    type: "Concours",
    descCourte: "Concours sur titres : entretien de 20 minutes avec le jury. Session 2027 (dates à confirmer CDG 971).",
    seoTitle: "Concours Aide-Soignant Territorial Guadeloupe 2027 | Evolutia",
    seoDesc: "Préparez le concours d'aide-soignant territorial en Guadeloupe : entretien jury de 20 min. Session 2027, diplôme d'État requis. Evolutia, Les Abymes.",
    accroche: "L'aide-soignant territorial exerce dans les EHPAD publics territoriaux, les services de soins à domicile et les structures médico-sociales des collectivités. Le concours sur titres repose sur un entretien unique de 20 minutes avec le jury.",
    epreuves: [
      { type: "Oral", label: "Entretien avec le jury (20 min dont 5 min d'exposé, coef. 1)", desc: "Exposé sur la formation, le parcours et le projet professionnels, puis échange permettant d'apprécier la capacité à s'intégrer dans l'environnement professionnel territorial, la motivation et l'aptitude à exercer les missions du cadre d'emplois." },
    ],
    programme: [
      "Environnement territorial : CCAS, EHPAD publics, maintien à domicile",
      "Construction de l'exposé de 5 minutes : parcours, projet, motivation",
      "Questions types du jury : bientraitance, travail en équipe, secret professionnel",
      "Enjeux du grand âge et de l'autonomie en Guadeloupe",
      "Simulations d'entretien filmées avec débriefing individuel",
      "Préparation du dossier d'inscription",
    ],
    conditions: [
      { voie: "Sur titres", condition: "Diplôme d'État d'aide-soignant (ou certificat d'aptitude / diplôme professionnel d'aide-soignant)" },
    ],
    duree: "15 à 25 heures",
    format: "Présentiel (Grand-Camp, Les Abymes)",
    tauxReussite: "85%",
    color: "#F5A623",
    accent: "#4BADD4",
    datesCles: [
      { label: "Inscriptions (session 2027)", date: "16 mars → 21 avril 2027*", statut: "bientot" },
      { label: "Épreuve d'entretien", date: "4 octobre 2027*", statut: "bientot" },
      { label: "*Dates du portail national", date: "À confirmer auprès du CDG 971", statut: "bientot" },
    ],
    faq: [
      { q: "Où travaille un aide-soignant territorial en Guadeloupe ?", a: "Dans les EHPAD et résidences autonomie gérés par les CCAS ou les communes, les services de soins infirmiers à domicile (SSIAD) territoriaux et certaines structures médico-sociales du Département." },
      { q: "Pourquoi passer le concours si j'ai déjà mon diplôme d'État ?", a: "Le diplôme permet d'exercer, mais le concours donne accès au statut de fonctionnaire territorial : sécurité de l'emploi, grille indiciaire, déroulement de carrière (aide-soignant de classe supérieure, puis auxiliaire de soins principal). Beaucoup de contractuels passent le concours pour être titularisés." },
      { q: "Comment se démarquer sur un entretien de 20 minutes ?", a: "En maîtrisant ce que les autres candidats négligent : le fonctionnement des collectivités, le rôle du CCAS, les enjeux territoriaux du vieillissement. Votre expérience de soin parle pour vous ; nous préparons le reste — exposé structuré et réponses aux questions institutionnelles." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=360",
  },

  "auxiliaire-puericulture-guadeloupe": {
    titre: "Auxiliaire de Puériculture",
    sousTitre: "Concours sur titres avec épreuve — classe normale",
    categorie: "Catégorie B",
    filiere: "Filière médico-sociale",
    type: "Concours",
    descCourte: "Concours sur titres : entretien de 20 minutes avec le jury. Épreuve le 1er mars 2027.",
    seoTitle: "Concours Auxiliaire de Puériculture Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez le concours d'auxiliaire de puériculture territorial en Guadeloupe : entretien de 20 min. Inscriptions sept.-oct. 2026, épreuve mars 2027.",
    accroche: "L'auxiliaire de puériculture territorial exerce en crèche municipale, en halte-garderie et en PMI. Le concours sur titres repose sur un entretien unique de 20 minutes : votre diplôme d'État vous rend éligible, la préparation de l'oral fait la différence.",
    epreuves: [
      { type: "Oral", label: "Entretien avec le jury (20 min dont 5 min d'exposé, coef. 1)", desc: "Exposé sur la formation, le parcours et le projet professionnels, puis échange permettant d'apprécier la capacité à s'intégrer dans l'environnement professionnel territorial, la motivation et l'aptitude à exercer les missions du cadre d'emplois." },
    ],
    programme: [
      "Environnement territorial : crèches municipales, PMI, politiques petite enfance",
      "Construction de l'exposé de 5 minutes : parcours, projet, motivation",
      "Questions types du jury : sécurité affective, hygiène, relation aux familles",
      "Enjeux de l'accueil du jeune enfant en Guadeloupe",
      "Simulations d'entretien filmées avec débriefing individuel",
      "Préparation du dossier d'inscription",
    ],
    conditions: [
      { voie: "Sur titres", condition: "Diplôme d'État d'auxiliaire de puériculture (ou autorisation d'exercice pour les ressortissants UE/EEE)" },
    ],
    duree: "15 à 25 heures",
    format: "Présentiel (Grand-Camp, Les Abymes)",
    tauxReussite: "85%",
    color: "#4BADD4",
    accent: "#F5A623",
    datesCles: [
      { label: "Inscriptions", date: "15 sept. → 21 oct. 2026", statut: "bientot" },
      { label: "Épreuve d'entretien", date: "1er mars 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Novembre 2026", statut: "ouvert" },
    ],
    faq: [
      { q: "Je travaille déjà en crèche comme contractuelle, le concours m'apporte quoi ?", a: "La titularisation : statut de fonctionnaire, sécurité de l'emploi, grille indiciaire et perspectives d'évolution (auxiliaire de puériculture de classe supérieure). Les collectivités privilégient les lauréates du concours pour les postes permanents." },
      { q: "Que demande le jury à l'entretien ?", a: "Au-delà de votre pratique professionnelle : votre connaissance du fonctionnement d'une commune, du rôle de la PMI, des normes d'accueil du jeune enfant, et votre projet professionnel en collectivité. L'exposé initial de 5 minutes doit être construit et répété." },
      { q: "Quand faut-il s'inscrire ?", a: "Les inscriptions sont ouvertes du 15 septembre au 21 octobre 2026 sur concours-territorial.fr, pour une épreuve le 1er mars 2027. Attention : aucune inscription tardive n'est acceptée. Nous conseillons de préparer l'entretien à partir de novembre 2026." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=361",
  },

  "agent-social-guadeloupe": {
    titre: "Agent Social Principal de 2e Classe",
    sousTitre: "Concours externe, interne et 3e voie",
    categorie: "Catégorie C",
    filiere: "Filière médico-sociale",
    type: "Concours",
    descCourte: "QCM de 45 minutes puis entretien de motivation. Épreuves le 5 octobre 2027.",
    seoTitle: "Concours Agent Social Principal Guadeloupe 2027 | Evolutia",
    seoDesc: "Préparez le concours d'agent social principal 2e classe en Guadeloupe : QCM + entretien. Inscriptions mars-avril 2027, épreuves octobre 2027. CPF.",
    accroche: "L'agent social territorial intervient auprès des personnes âgées, des familles et des publics fragiles : aide à domicile, accompagnement social, structures d'accueil. Le concours de principal de 2e classe (catégorie C) combine un QCM et un entretien de motivation.",
    epreuves: [
      { type: "Écrit", label: "QCM (45 min, coef. 1)", desc: "Questionnaire à choix multiples portant sur des notions élémentaires d'organisation et de fonctionnement des collectivités locales, et sur la compréhension de consignes élémentaires d'hygiène et de sécurité (voie externe)." },
      { type: "Oral", label: "Entretien avec le jury (15 min, coef. 2)", desc: "Entretien permettant d'apprécier la motivation du candidat et son aptitude à exercer les missions incombant aux membres du cadre d'emplois. En interne et 3e voie, l'entretien s'appuie sur l'expérience professionnelle." },
    ],
    programme: [
      "Organisation et fonctionnement des collectivités locales — l'essentiel pour le QCM",
      "Hygiène et sécurité : consignes élémentaires et situations types",
      "Missions de l'agent social : publics, structures, déontologie",
      "Entraînements QCM chronométrés en conditions réelles",
      "Simulations d'entretien de motivation avec débriefing",
      "Connaissance de l'action sociale en Guadeloupe (CCAS, Département)",
    ],
    conditions: [
      { voie: "Externe", condition: "Diplôme de niveau 3 (CAP/BEP, DEAES…) ou qualification reconnue équivalente" },
      { voie: "Interne", condition: "Fonctionnaires et agents publics — conditions de services précisées par l'organisateur" },
      { voie: "3e voie", condition: "4 ans au moins d'activités professionnelles, de mandats d'élu local ou de responsabilités associatives" },
    ],
    duree: "40 à 60 heures",
    format: "Présentiel (Grand-Camp, Les Abymes)",
    tauxReussite: "85%",
    color: "#1B3A6B",
    accent: "#4BADD4",
    datesCles: [
      { label: "Inscriptions", date: "16 mars → 21 avril 2027", statut: "bientot" },
      { label: "Épreuves", date: "5 octobre 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Printemps 2027", statut: "ouvert" },
    ],
    faq: [
      { q: "Quel diplôme faut-il pour le concours d'agent social principal ?", a: "En voie externe, un diplôme de niveau 3 : CAP, BEP, ou le DEAES (diplôme d'État d'accompagnant éducatif et social). Une qualification reconnue équivalente est également acceptée. Les voies interne et 3e voie sont ouvertes sans condition de diplôme." },
      { q: "Où exerce un agent social territorial ?", a: "Principalement dans les CCAS (aide à domicile, portage de repas, accompagnement des personnes âgées), les EHPAD territoriaux, les résidences autonomie et les services sociaux des communes." },
      { q: "Le QCM est-il difficile ?", a: "Il est accessible mais piégeux sans préparation : les questions portent sur l'organisation des collectivités (maire, conseil municipal, intercommunalité…) et l'hygiène et la sécurité, des sujets rarement maîtrisés spontanément. Nos entraînements chronométrés couvrent tout le programme." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=364",
  },

  "atsem-guadeloupe": {
    titre: "ATSEM Principal de 2e Classe",
    sousTitre: "Concours externe, interne et 3e voie",
    categorie: "Catégorie C",
    filiere: "Filière médico-sociale",
    type: "Concours",
    descCourte: "QCM de 20 questions puis entretien. CAP AEPE requis en externe. Épreuves le 29 septembre 2027.",
    seoTitle: "Concours ATSEM Guadeloupe 2027 : Préparation Complète | Evolutia",
    seoDesc: "Préparez le concours d'ATSEM principal 2e classe en Guadeloupe : QCM 45 min + entretien 15 min. CAP AEPE requis. Inscriptions mars-avril 2027. CPF.",
    accroche: "L'ATSEM (agent territorial spécialisé des écoles maternelles) assiste les enseignants de maternelle et accompagne les enfants tout au long de la journée scolaire. Un concours très demandé en Guadeloupe : le QCM et l'entretien se préparent sérieusement pour se démarquer.",
    epreuves: [
      { type: "Écrit", label: "Externe — QCM de 20 questions (45 min, coef. 1)", desc: "Questions à choix multiples portant sur des situations concrètes habituellement rencontrées par les ATSEM dans l'exercice de leurs fonctions." },
      { type: "Écrit", label: "Interne / 3e voie — Questions à réponses courtes (2h, coef. 1)", desc: "Série de 3 à 5 questions à partir d'un dossier succinct portant sur les situations rencontrées par un ATSEM en exercice." },
      { type: "Oral", label: "Entretien avec le jury (15 à 20 min, coef. 2)", desc: "En externe : entretien de 15 minutes sur l'aptitude, la motivation et la connaissance de l'environnement professionnel. En interne et 3e voie : présentation de l'expérience (5 min) puis conversation, le cas échéant sous forme de mise en situation (20 min)." },
    ],
    programme: [
      "Le métier d'ATSEM : rôle auprès des enfants, de l'enseignant, de la collectivité",
      "Situations professionnelles types : hygiène, sécurité, activités, cantine, sieste",
      "Entraînements QCM chronométrés sur les 20 questions types",
      "Environnement professionnel : école maternelle, commune, communauté éducative",
      "Simulations d'entretien avec mises en situation",
      "Focus Guadeloupe : recrutements des communes, réalités du terrain",
    ],
    conditions: [
      { voie: "Externe", condition: "CAP Accompagnant éducatif petite enfance (ex-CAP petite enfance) ou qualification reconnue équivalente" },
      { voie: "Interne", condition: "Fonctionnaires et agents publics justifiant de services effectifs auprès de jeunes enfants — conditions précisées par l'organisateur" },
      { voie: "3e voie", condition: "4 ans au moins d'activités professionnelles auprès de jeunes enfants, de mandats d'élu local ou de responsabilités associatives" },
    ],
    duree: "40 à 60 heures",
    format: "Présentiel (Grand-Camp, Les Abymes)",
    tauxReussite: "85%",
    color: "#F5A623",
    accent: "#1B3A6B",
    datesCles: [
      { label: "Inscriptions", date: "16 mars → 21 avril 2027", statut: "bientot" },
      { label: "Épreuves", date: "29 septembre 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Printemps 2027", statut: "ouvert" },
    ],
    faq: [
      { q: "Le CAP AEPE est-il obligatoire pour devenir ATSEM ?", a: "Pour le concours externe, oui : le CAP Accompagnant éducatif petite enfance (ou une qualification équivalente) est exigé. Si vous êtes déjà agent public ou si vous justifiez de 4 ans d'expérience auprès de jeunes enfants, les voies interne et 3e voie sont possibles sans ce diplôme." },
      { q: "Le concours d'ATSEM est-il très sélectif en Guadeloupe ?", a: "Oui, c'est l'un des concours de catégorie C les plus demandés : le nombre de candidates dépasse largement le nombre de postes. Le QCM élimine beaucoup de candidates non préparées, et l'entretien (coefficient 2) départage les admissibles — la préparation fait clairement la différence." },
      { q: "Que faire après la réussite au concours ?", a: "Vous êtes inscrite sur liste d'aptitude pendant 4 ans maximum et devez candidater auprès des communes de Guadeloupe pour être recrutée. Nous conseillons de postuler rapidement et largement — la liste d'aptitude ne vaut pas recrutement automatique." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=363",
  },

  "auxiliaire-soins-guadeloupe": {
    titre: "Auxiliaire de Soins Principal de 2e Classe",
    sousTitre: "Concours sur titres avec épreuve",
    categorie: "Catégorie C",
    filiere: "Filière médico-sociale",
    type: "Concours",
    descCourte: "Concours sur titres : entretien de 15 minutes avec le jury. Épreuve le 4 octobre 2027.",
    seoTitle: "Concours Auxiliaire de Soins Principal Guadeloupe 2027 | Evolutia",
    seoDesc: "Préparez le concours d'auxiliaire de soins principal 2e classe en Guadeloupe : entretien 15 min. Spécialités AMP, assistant dentaire. Épreuves oct. 2027.",
    accroche: "L'auxiliaire de soins territorial exerce notamment comme aide médico-psychologique ou assistant dentaire dans les structures des collectivités. Le concours sur titres repose sur un entretien unique de 15 minutes — court, donc décisif.",
    epreuves: [
      { type: "Oral", label: "Entretien avec le jury (15 min, coef. 1)", desc: "Entretien permettant d'apprécier les capacités professionnelles du candidat, ses motivations et son aptitude à exercer les missions incombant aux membres du cadre d'emplois." },
    ],
    programme: [
      "Environnement territorial : CCAS, EHPAD, centres de santé municipaux",
      "Présentation du parcours et du projet professionnel en quelques minutes",
      "Questions types du jury selon la spécialité (AMP / assistant dentaire)",
      "Déontologie, bientraitance, travail en équipe pluridisciplinaire",
      "Simulations d'entretien filmées avec débriefing individuel",
      "Préparation du dossier d'inscription",
    ],
    conditions: [
      { voie: "Sur titres — spécialité aide médico-psychologique", condition: "DEAES (accompagnement de la vie en structure collective), DEAMP, CAFAMP ou DEAVS" },
      { voie: "Sur titres — spécialité assistant dentaire", condition: "Titre ou diplôme de niveau 3 du domaine dentaire inscrit au RNCP" },
    ],
    duree: "15 à 25 heures",
    format: "Présentiel (Grand-Camp, Les Abymes)",
    tauxReussite: "85%",
    color: "#4BADD4",
    accent: "#1B3A6B",
    datesCles: [
      { label: "Inscriptions", date: "16 mars → 21 avril 2027", statut: "bientot" },
      { label: "Épreuve d'entretien", date: "4 octobre 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Été 2027", statut: "ouvert" },
    ],
    faq: [
      { q: "Quelles spécialités sont ouvertes au concours d'auxiliaire de soins ?", a: "Les principales spécialités sont l'aide médico-psychologique (accessible avec le DEAES, le DEAMP ou le DEAVS) et l'assistant dentaire (titre de niveau 3 du domaine dentaire). Vérifiez les spécialités effectivement ouvertes lors de la session auprès de l'organisateur." },
      { q: "Comment réussir un entretien de seulement 15 minutes ?", a: "En allant à l'essentiel : une présentation de parcours calibrée, des exemples concrets de situations professionnelles, et une vraie connaissance de l'environnement territorial (CCAS, EHPAD publics). 15 minutes ne pardonnent pas l'improvisation — chaque minute se prépare." },
      { q: "Quelle évolution de carrière ensuite ?", a: "Le grade de principal de 2e classe permet ensuite d'évoluer vers le grade de principal de 1re classe par avancement. Certains agents poursuivent vers le concours d'aide-soignant territorial (catégorie B) après obtention du diplôme d'État correspondant." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=362",
  },

  /* ─────────────────────── FILIÈRE TECHNIQUE ─────────────────────── */

  "ingenieur-territorial-guadeloupe": {
    titre: "Ingénieur Territorial",
    sousTitre: "Concours externe et interne + examen professionnel de promotion interne",
    categorie: "Catégorie A",
    filiere: "Filière technique",
    type: "Concours",
    descCourte: "Note de spécialité (5h, coef. 5) et entretien de 40 minutes. Inscriptions déc. 2026 - janv. 2027.",
    seoTitle: "Préparation Concours Ingénieur Territorial Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez le concours d'ingénieur territorial en Guadeloupe : note de spécialité 5h, entretien 40 min. Session 2027, financement CPF. Evolutia, Les Abymes.",
    accroche: "Le concours d'ingénieur territorial ouvre l'accès aux postes d'encadrement technique des collectivités : infrastructures, bâtiment, réseaux, informatique, prévention des risques. En voie externe, tout repose sur deux épreuves à fort coefficient — une note de 5 heures et un entretien de 40 minutes.",
    epreuves: [
      { type: "Écrit", label: "Externe — Note à partir d'un dossier de spécialité (5h, coef. 5)", desc: "Rédaction d'une note à partir de l'analyse d'un dossier, tenant compte du contexte technique, économique ou juridique. Le dossier porte sur la spécialité choisie à l'inscription (infrastructures, bâtiment, réseaux, informatique, prévention des risques…)." },
      { type: "Écrit", label: "Interne — 3 épreuves écrites", desc: "Mathématiques et physique appliquées (4h, coef. 3), note sur dossier de spécialité (4h, coef. 3) et établissement d'un projet ou étude dans l'option choisie (8h, coef. 7)." },
      { type: "Oral", label: "Entretien avec le jury (40 min, coef. 5)", desc: "Première partie : questions sur l'option choisie au sein de la spécialité. Seconde partie : aptitude à s'intégrer dans l'environnement professionnel et à résoudre les problèmes techniques ou d'encadrement d'un ingénieur. Fiche individuelle de renseignement transmise à l'inscription (non notée). Épreuve facultative de langue possible." },
      { type: "Examen pro.", label: "Promotion interne — écrit + entretien", desc: "Pour les techniciens avec 8 ans de services en catégorie B : note sur dossier (4h, coef. 3), projet ou étude dans l'option choisie (4h, coef. 5) et entretien de 40 minutes (coef. 5). Voie spécifique sur entretien seul pour les directeurs des services techniques de communes de moins de 20 000 habitants." },
    ],
    programme: [
      "Méthodologie de la note sur dossier de spécialité — la seule épreuve écrite externe, coef. 5",
      "Approfondissement technique par spécialité (infrastructures, bâtiment, informatique…)",
      "Culture territoriale : commande publique, finances, conduite de projet en collectivité",
      "Enjeux techniques de la Guadeloupe : eau, énergie, risques naturels, aménagement",
      "Préparation de l'entretien de 40 minutes : questions d'option + posture professionnelle",
      "Simulations d'oral filmées avec débriefing individuel",
    ],
    conditions: [
      { voie: "Externe", condition: "Diplôme d'ingénieur, d'architecte ou diplôme scientifique/technique de niveau Bac+5 correspondant à l'une des spécialités" },
      { voie: "Interne (concours)", condition: "Fonctionnaires et agents publics comptant au moins 4 ans de services publics" },
      { voie: "Examen pro. (promotion interne)", condition: "Techniciens territoriaux justifiant de 8 ans de services effectifs dans un cadre d'emplois technique de catégorie B" },
    ],
    duree: "120 à 180 heures",
    format: "Présentiel (Grand-Camp, Les Abymes) + distanciel",
    tauxReussite: "82%",
    color: "#1B3A6B",
    accent: "#4BADD4",
    datesCles: [
      { label: "Inscriptions concours (session 2027)", date: "8 déc. 2026 → 13 jan. 2027", statut: "bientot" },
      { label: "Épreuves écrites", date: "16 juin 2027", statut: "bientot" },
      { label: "Examen pro. promotion interne 2026", date: "Épreuves passées le 18 juin 2026", statut: "ferme" },
    ],
    faq: [
      { q: "Quelles sont exactement les épreuves du concours externe d'ingénieur ?", a: "Deux épreuves seulement, mais à très fort coefficient : une note à partir d'un dossier de spécialité (5 heures, coefficient 5) et un entretien de 40 minutes (coefficient 5) portant d'abord sur l'option choisie, puis sur votre aptitude professionnelle. Une épreuve facultative de langue peut s'y ajouter. Il n'y a pas d'épreuve de culture générale." },
      { q: "Le concours externe exige-t-il Bac+5 ?", a: "Oui : diplôme d'ingénieur, d'architecte ou autre diplôme scientifique ou technique sanctionnant au moins 5 années d'études supérieures dans l'une des spécialités du concours. Les titulaires d'un Bac+3 technique peuvent viser le concours de technicien puis la promotion interne." },
      { q: "Qu'est-ce que l'examen professionnel de promotion interne ?", a: "Il permet aux techniciens territoriaux justifiant de 8 ans de services en catégorie B technique d'accéder au grade d'ingénieur sans passer le concours : une note sur dossier (4h), un projet ou étude (4h) et un entretien de 40 minutes. La session 2026 a eu lieu le 18 juin — nous préparons déjà la suivante." },
      { q: "Quelle spécialité choisir en Guadeloupe ?", a: "Les collectivités guadeloupéennes recrutent surtout en infrastructures et réseaux (eau, assainissement, voirie), bâtiment et construction, et prévention des risques (sismique, cyclonique). Choisissez la spécialité de votre formation initiale : le jury évalue une expertise réelle." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=327",
  },

  "ingenieur-chef-guadeloupe": {
    titre: "Ingénieur en Chef",
    sousTitre: "Concours externe et interne — Catégorie A+",
    categorie: "Catégorie A+",
    filiere: "Filière technique",
    type: "Concours",
    descCourte: "Trois écrits de 5h, entretien sur dossier, mise en situation collective. Le concours technique le plus exigeant.",
    seoTitle: "Préparation Concours Ingénieur en Chef Guadeloupe 2026 | Evolutia",
    seoDesc: "Préparez le concours d'ingénieur en chef territorial : 3 écrits de 5h, grand oral, mise en situation collective. Organisé par le CNFPT. Evolutia Formation.",
    accroche: "Le concours d'ingénieur en chef territorial (A+), organisé par le CNFPT, mène aux plus hautes fonctions techniques : direction générale des services techniques, pilotage de grandes directions. Trois épreuves écrites de 5 heures et des oraux exigeants — une préparation d'excellence s'impose.",
    epreuves: [
      { type: "Écrit", label: "Note de synthèse et de propositions technique (5h, coef. 5)", desc: "Analyse d'un dossier portant sur un sujet technique dans l'une des cinq options : ingénierie environnementale ; constructions publiques, gestion immobilière, énergie ; aménagement, déplacements et urbanisme ; réseaux techniques urbains et infrastructures ; systèmes d'information et de communication." },
      { type: "Écrit", label: "Note de synthèse et de propositions — conduite de projet (5h, coef. 4)", desc: "Dossier portant sur une conduite de projet soulevant un problème d'organisation ou de gestion rencontré par une collectivité territoriale (coef. 5 en voie interne)." },
      { type: "Écrit", label: "Composition sur une question de société contemporaine (5h, coef. 3)", desc: "Apprécier l'aptitude du candidat à exprimer une analyse des faits et une interprétation personnelle et argumentée sur le sujet proposé." },
      { type: "Oral", label: "Entretien avec le jury à partir d'un dossier (30 min, coef. 5)", desc: "À partir d'un dossier fourni par le candidat : parcours, réalisations, capacités d'analyse et de synthèse, motivation et capacité à exercer les fonctions d'ingénieur en chef. Seul l'entretien est noté." },
      { type: "Oral", label: "Mise en situation professionnelle collective (45 min, coef. 2)", desc: "30 minutes de mise en situation collective puis 15 minutes de compte-rendu et d'échanges individuels avec le jury. S'y ajoute une épreuve orale de langue vivante (30 min, coef. 1)." },
    ],
    programme: [
      "Méthodologie des notes de synthèse et de propositions — entraînements 5h en conditions réelles",
      "Composition sur les questions de société : culture générale contemporaine et argumentation",
      "Constitution du dossier candidat et préparation de l'entretien de 30 minutes",
      "Entraînement aux mises en situation collectives (leadership, écoute, synthèse)",
      "Gouvernance territoriale et politiques publiques : le niveau A+ attendu",
      "Coaching individuel intensif sur la posture de cadre dirigeant",
    ],
    conditions: [
      { voie: "Externe", condition: "Titres et diplômes spécifiques (écoles d'ingénieurs, architectes…) ou qualification reconnue équivalente" },
      { voie: "Interne", condition: "Fonctionnaires et agents publics remplissant les conditions de services fixées par le statut particulier" },
    ],
    duree: "80 à 120 heures",
    format: "Présentiel (Grand-Camp) + coaching individuel en distanciel",
    tauxReussite: "79%",
    color: "#1B3A6B",
    accent: "#F5A623",
    datesCles: [
      { label: "Épreuves écrites (session 2026)", date: "7 septembre 2026", statut: "bientot" },
      { label: "Inscriptions (session 2026)", date: "Clôturées — CNFPT", statut: "ferme" },
      { label: "Préparation aux oraux d'admission", date: "Dès les résultats d'admissibilité", statut: "ouvert" },
    ],
    faq: [
      { q: "Quelles sont les épreuves écrites du concours d'ingénieur en chef ?", a: "Trois épreuves de 5 heures chacune : une note de synthèse et de propositions sur un sujet technique dans l'option choisie (coef. 5), une note sur une conduite de projet (coef. 4 en externe), et une composition sur une question de société contemporaine (coef. 3). L'admissibilité exige donc autant de culture générale que d'expertise technique." },
      { q: "En quoi consiste la mise en situation professionnelle collective ?", a: "C'est une épreuve d'admission originale : 30 minutes de travail collectif avec d'autres candidats sur un cas donné, puis 15 minutes de compte-rendu individuel devant le jury. Elle évalue le leadership, l'écoute et la capacité de synthèse — des compétences qui s'entraînent en conditions réelles." },
      { q: "Qui organise ce concours et où se passent les épreuves ?", a: "Le concours d'ingénieur en chef est organisé nationalement par le CNFPT (et non par le CDG 971). Les épreuves écrites de la session 2026 ont lieu le 7 septembre 2026. Notre préparation à distance et en présentiel s'adapte à cette organisation nationale." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=409",
  },

  "technicien-territorial-guadeloupe": {
    titre: "Technicien Territorial & Technicien Principal",
    sousTitre: "Concours et examens professionnels d'avancement de grade",
    categorie: "Catégorie B",
    filiere: "Filière technique",
    type: "Concours + Examen pro.",
    descCourte: "Examens pro. technicien principal : rapport technique (3h) + entretien. Épreuves le 15 avril 2027.",
    seoTitle: "Concours et Examens Technicien Territorial Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez le concours de technicien territorial et les examens de technicien principal en Guadeloupe : rapport technique, entretien. Épreuves avril 2027.",
    accroche: "Le technicien territorial est le pivot des services techniques des collectivités. Au calendrier 2026-2027 : les examens professionnels de technicien principal (1re et 2e classe, avancement de grade et promotion interne), avec inscriptions à l'automne 2026. La prochaine session du concours de technicien sera annoncée par le CDG 971.",
    epreuves: [
      { type: "Écrit", label: "Examens pro. — Rapport technique avec propositions (3h, coef. 1)", desc: "Rédaction d'un rapport technique portant sur la spécialité choisie, assorti de propositions opérationnelles. Épreuve commune aux examens de technicien principal de 1re et de 2e classe. Note minimale de 5/20 pour accéder à l'oral." },
      { type: "Oral", label: "Examens pro. — Entretien (20 min dont 5 min d'exposé, coef. 1 à 2)", desc: "Exposé sur l'expérience professionnelle puis questions techniques et d'aptitude. Coefficient 2 pour la 1re classe (accent sur l'encadrement) et la promotion interne, coefficient 1 pour la 2e classe en avancement de grade." },
      { type: "Écrit", label: "Concours technicien — Épreuves écrites (3h, coef. 1)", desc: "En externe : réponses à des questions techniques à partir d'un dossier de spécialité. En interne et 3e voie : élaboration d'un rapport technique à partir d'un dossier. Prochaine session : dates à confirmer par le CDG 971." },
    ],
    programme: [
      "Méthodologie du rapport technique avec propositions opérationnelles",
      "Connaissances techniques par spécialité (bâtiment, voirie, réseaux, informatique…)",
      "Entraînements écrits corrigés individuellement sur sujets d'annales",
      "Construction de l'exposé d'expérience professionnelle (5 minutes)",
      "Simulations d'entretien adaptées à l'examen visé (2e classe, 1re classe, promotion interne)",
      "Veille sur le calendrier CDG 971 pour la prochaine session du concours",
    ],
    conditions: [
      { voie: "Examen pro. 2e classe (avancement)", condition: "Techniciens ayant atteint le 6e échelon du grade et justifiant de 3 ans de services effectifs en catégorie B" },
      { voie: "Examen pro. 1re classe (avancement)", condition: "Techniciens principaux de 2e classe avec 1 an dans le 6e échelon et 3 ans de services effectifs en catégorie B" },
      { voie: "Examen pro. 2e classe (promotion interne)", condition: "Agents de maîtrise justifiant de 8 ans de services effectifs, ou adjoints techniques principaux justifiant de 10 ans, dont 5 ans en cadre d'emplois technique territorial" },
      { voie: "Concours (externe)", condition: "Baccalauréat technologique ou professionnel, ou diplôme de niveau 4 technico-professionnel correspondant à une spécialité" },
    ],
    duree: "60 à 120 heures",
    format: "Présentiel (Grand-Camp, Les Abymes) + distanciel",
    tauxReussite: "87%",
    color: "#4BADD4",
    accent: "#1B3A6B",
    datesCles: [
      { label: "Inscriptions examens pro. technicien principal", date: "13 oct. → 18 nov. 2026", statut: "bientot" },
      { label: "Épreuves écrites examens pro.", date: "15 avril 2027", statut: "bientot" },
      { label: "Prochain concours de technicien", date: "À confirmer — CDG 971", statut: "bientot" },
    ],
    faq: [
      { q: "Quelle différence entre avancement de grade et promotion interne pour technicien principal de 2e classe ?", a: "L'avancement de grade s'adresse aux techniciens (catégorie B) qui montent en grade dans leur cadre d'emplois. La promotion interne s'adresse aux agents de catégorie C (agents de maîtrise avec 8 ans de services, adjoints techniques principaux avec 10 ans) qui accèdent à la catégorie B. Les épreuves sont proches — rapport technique de 3h puis entretien — mais les jurys n'attendent pas la même chose." },
      { q: "Quand aura lieu le prochain concours de technicien territorial ?", a: "La dernière session s'est tenue le 9 avril 2026. La prochaine session n'est pas encore annoncée : les concours de technicien sont généralement organisés tous les deux ans. Inscrivez-vous à notre veille pour être alerté dès la publication des dates par le CDG 971." },
      { q: "Le rapport technique est-il difficile ?", a: "C'est une épreuve exigeante en 3 heures : analyser un dossier technique de spécialité, en tirer un diagnostic et formuler des propositions opérationnelles chiffrées et réalistes. Une note sous 5/20 est éliminatoire. La méthodologie s'acquiert par des entraînements corrigés — c'est le cœur de notre préparation." },
    ],
    sourceOfficielle: "https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000023036811",
  },

  "adjoint-technique-principal-guadeloupe": {
    titre: "Adjoint Technique Principal de 2e Classe",
    sousTitre: "Concours externe, interne et 3e voie",
    categorie: "Catégorie C",
    filiere: "Filière technique",
    type: "Concours",
    descCourte: "Questions techniques à réponses courtes puis épreuves d'admission par spécialité. Session 2027.",
    seoTitle: "Concours Adjoint Technique Principal Guadeloupe 2027 | Evolutia",
    seoDesc: "Préparez le concours d'adjoint technique principal 2e classe en Guadeloupe : écrit technique + entretien. Inscriptions mai-juin 2027, épreuves nov. 2027.",
    accroche: "Le concours d'adjoint technique principal de 2e classe (catégorie C) recrute les agents qualifiés des services techniques : bâtiment, espaces verts, voirie, restauration, mécanique. Les épreuves privilégient les connaissances techniques concrètes de la spécialité choisie.",
    epreuves: [
      { type: "Écrit", label: "Questions techniques à réponses courtes (1h à 2h, coef. 2 à 3)", desc: "Vérification des connaissances techniques de la spécialité, notamment en matière d'hygiène et de sécurité, au moyen de questions à réponses courtes, tableaux ou graphiques à compléter. Selon les sessions, un cas pratique de spécialité peut s'y ajouter (2h, coef. 3)." },
      { type: "Oral", label: "Entretien dans l'option choisie (15 min, coef. 3 à 4)", desc: "Entretien permettant d'apprécier les connaissances, les aptitudes et la motivation. En externe s'ajoute une interrogation orale sur l'hygiène, la sécurité et l'environnement professionnel (15 min, coef. 2)." },
      { type: "Pratique", label: "Épreuve pratique dans l'option (interne et 3e voie, coef. 3)", desc: "Accomplissement d'une ou plusieurs tâches se rapportant à la maîtrise des techniques et instruments de l'option choisie (durée de 1h à 4h selon l'option)." },
    ],
    programme: [
      "Connaissances techniques de la spécialité : révisions ciblées et fiches pratiques",
      "Hygiène et sécurité au travail : réglementation, EPI, gestes et postures",
      "Entraînements aux questions à réponses courtes et aux tableaux à compléter",
      "Préparation de l'épreuve pratique selon l'option (interne / 3e voie)",
      "Simulations d'entretien avec questions techniques types",
      "Environnement professionnel : la collectivité, le service technique, la chaîne hiérarchique",
    ],
    conditions: [
      { voie: "Externe", condition: "Titre ou diplôme de niveau 3 (CAP/BEP) sanctionnant une formation technique et professionnelle dans la spécialité" },
      { voie: "Interne", condition: "Fonctionnaires et agents publics — conditions de services précisées par l'organisateur" },
      { voie: "3e voie", condition: "4 ans au moins d'activités professionnelles dans le domaine, de mandats d'élu local ou de responsabilités associatives" },
    ],
    duree: "50 à 70 heures",
    format: "Présentiel (Grand-Camp, Les Abymes) + ateliers pratiques",
    tauxReussite: "85%",
    color: "#F5A623",
    accent: "#4BADD4",
    datesCles: [
      { label: "Inscriptions (session 2027)", date: "4 mai → 9 juin 2027", statut: "bientot" },
      { label: "Épreuves", date: "25 novembre 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Printemps 2027", statut: "ouvert" },
    ],
    faq: [
      { q: "Quelles spécialités sont proposées au concours ?", a: "Les spécialités classiques : bâtiment et travaux publics, espaces naturels et espaces verts, voirie et réseaux divers, restauration, environnement et hygiène, mécanique et électromécanique, conduite de véhicules… Les spécialités effectivement ouvertes pour la session 2027 seront précisées par l'organisateur à l'ouverture des inscriptions." },
      { q: "Je n'ai pas de CAP, puis-je me présenter ?", a: "En voie externe, un titre de niveau 3 est requis. Mais si vous êtes déjà agent public, la voie interne est ouverte sans condition de diplôme ; et si vous justifiez de 4 ans d'activité professionnelle dans le domaine, la 3e voie est possible." },
      { q: "En quoi consiste l'épreuve pratique ?", a: "Pour les voies interne et 3e voie, l'admission comporte une épreuve pratique dans l'option choisie : réaliser une ou plusieurs tâches concrètes du métier (durée de 1 à 4 heures selon l'option). Le jury évalue les gestes techniques, le respect des consignes de sécurité et l'organisation du travail." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=333",
  },

  "agent-de-maitrise-guadeloupe": {
    titre: "Agent de Maîtrise",
    sousTitre: "Concours externe, interne et 3e voie",
    categorie: "Catégorie C",
    filiere: "Filière technique",
    type: "Concours",
    descCourte: "Mathématiques et cas pratique (externe), connaissances techniques (interne), entretien. Épreuves janv. 2027.",
    seoTitle: "Préparation Concours Agent de Maîtrise Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez le concours d'agent de maîtrise territorial en Guadeloupe : maths, cas pratique, entretien. Inscriptions sept.-oct. 2026, épreuves janvier 2027.",
    accroche: "L'agent de maîtrise territorial encadre les équipes techniques des collectivités : espaces verts, bâtiment, voirie. Les inscriptions ouvrent le 1er septembre 2026 pour des épreuves le 28 janvier 2027 — c'est maintenant qu'il faut lancer la préparation.",
    epreuves: [
      { type: "Écrit", label: "Externe — Mathématiques (2h, coef. 2) + cas pratique (2h, coef. 3)", desc: "Problèmes d'application sur le programme de mathématiques, puis résolution d'un cas pratique exposé dans un dossier portant sur les problèmes rencontrés par un agent de maîtrise dans la spécialité choisie." },
      { type: "Écrit", label: "Interne / 3e voie — Connaissances techniques (2h, coef. 2) + cas pratique (2h, coef. 3)", desc: "Vérification des connaissances techniques, notamment en hygiène et sécurité, au moyen de questionnaires, tableaux ou graphiques (aucune épreuve rédactionnelle), puis résolution d'un cas pratique de spécialité." },
      { type: "Oral", label: "Entretien avec le jury (15 min, coef. 4)", desc: "Aptitude à s'intégrer dans l'environnement professionnel, motivation, connaissances en hygiène et sécurité, et capacité d'encadrement d'agents de catégorie C. En interne et 3e voie, l'entretien débute par un exposé de 5 minutes sur l'expérience." },
    ],
    programme: [
      "Remise à niveau en mathématiques appliquées (voie externe) — programme officiel",
      "Méthodologie du cas pratique : diagnostic, organisation du chantier, propositions",
      "Hygiène et sécurité : réglementation, évaluation des risques, EPI",
      "Management d'équipe technique : consignes, planning, contrôle qualité",
      "Entraînements chronométrés sur sujets d'annales corrigés",
      "Simulations d'entretien avec mise en situation d'encadrement",
    ],
    conditions: [
      { voie: "Externe", condition: "Deux titres ou diplômes de niveau 3 (CAP/BEP) sanctionnant une formation technique et professionnelle, ou qualifications équivalentes" },
      { voie: "Interne", condition: "Fonctionnaires et agents publics — conditions de services précisées par l'organisateur" },
      { voie: "3e voie", condition: "4 ans au moins d'activités professionnelles, de mandats d'élu local ou de responsabilités associatives" },
    ],
    duree: "60 à 80 heures",
    format: "Présentiel (Grand-Camp, Les Abymes) + ateliers pratiques",
    tauxReussite: "84%",
    color: "#4BADD4",
    accent: "#1B3A6B",
    datesCles: [
      { label: "Inscriptions", date: "1er sept. → 7 oct. 2026", statut: "ouvert" },
      { label: "Épreuves", date: "28 janvier 2027", statut: "bientot" },
      { label: "Démarrage préparation conseillé", date: "Immédiat — 4 mois avant les épreuves", statut: "ouvert" },
    ],
    faq: [
      { q: "Le concours externe exige-t-il vraiment deux diplômes ?", a: "Oui, particularité de ce concours : la voie externe exige deux titres ou diplômes de niveau 3 (CAP/BEP) sanctionnant une formation technique et professionnelle, ou des qualifications reconnues équivalentes. Si vous n'en avez qu'un, la voie interne (si vous êtes agent public) ou la 3e voie peuvent s'appliquer." },
      { q: "L'épreuve de mathématiques est-elle difficile ?", a: "Elle porte sur un programme défini (arithmétique, géométrie, unités, pourcentages appliqués aux situations techniques) et représente le principal obstacle des candidats externes. Une remise à niveau structurée sur 2 à 3 mois suffit généralement — c'est intégré à notre préparation." },
      { q: "Quelles sont les dates à retenir ?", a: "Inscriptions du 1er septembre au 7 octobre 2026 sur concours-territorial.fr, épreuves écrites le 28 janvier 2027. Compte tenu de l'épreuve de mathématiques et du cas pratique, nous recommandons de commencer la préparation dès septembre 2026." },
    ],
    sourceOfficielle: "https://www.concours-territorial.fr/session.aspx?id=331",
  },

  /* ─────────────────────── TOUTES FILIÈRES ─────────────────────── */

  "preparation-oraux-concours-guadeloupe": {
    titre: "Préparation aux Oraux",
    sousTitre: "Toutes catégories — tous concours et examens territoriaux",
    categorie: "Toutes catégories",
    filiere: "Toutes filières",
    type: "Coaching",
    descCourte: "Simulations de jury filmées, débriefing et coaching individuel — pour tout concours ou examen territorial.",
    seoTitle: "Préparation Oraux Concours Territoriaux Guadeloupe 2026-2027 | Evolutia",
    seoDesc: "Préparez les épreuves orales des concours territoriaux en Guadeloupe : simulations de jury filmées, coaching posture et prise de parole. Evolutia, Les Abymes.",
    accroche: "L'oral est souvent l'épreuve décisive qui fait la différence entre deux candidats de même niveau — et pour de nombreux concours médico-sociaux, c'est l'épreuve unique. Nos sessions intensives reproduisent les conditions réelles du jury. En quelques séances, vous transformez votre stress en confiance et votre discours en conviction.",
    epreuves: [
      { type: "Simulation", label: "Jury blanc en conditions réelles", desc: "Entretien filmé reproduisant exactement les conditions du concours visé : durée officielle, composition du jury, exposé initial chronométré. Analyse vidéo post-entretien." },
      { type: "Débriefing", label: "Analyse détaillée fond + forme", desc: "Retour point par point sur le contenu (arguments, connaissances territoriales), la forme (posture, voix, regard), la gestion du temps et l'attitude face aux relances du jury." },
      { type: "Coaching", label: "Séances individuelles de progression", desc: "Travail ciblé sur les points faibles identifiés lors des simulations. Techniques de respiration, ancrage, reformulation, gestion des questions déstabilisantes." },
    ],
    programme: [
      "Techniques de prise de parole en public et gestion du stress avant l'épreuve",
      "Construction d'un exposé de parcours percutant, calibré sur la durée officielle (5 à 10 min)",
      "Réponses aux questions difficiles et déstabilisantes du jury territorial",
      "Langage corporel : posture, regard, gestuelle, voix — travail pratique",
      "Simulations filmées par concours visé (toutes filières, toutes catégories)",
      "Séances de débriefing individuel avec progression mesurée entre chaque simulation",
    ],
    conditions: [
      { voie: "Tous profils", condition: "Candidat(e) à un concours ou examen professionnel territorial, toutes catégories (A, B, C) et toutes filières" },
    ],
    duree: "20 à 40 heures",
    format: "Présentiel exclusivement (Grand-Camp, Les Abymes)",
    tauxReussite: "91%",
    color: "#F5A623",
    accent: "#1B3A6B",
    datesCles: [
      { label: "Concours sur titres (entretien unique)", date: "Sessions en continu toute l'année", statut: "ouvert" },
      { label: "Oraux d'admission après écrits", date: "Dès les résultats d'admissibilité", statut: "ouvert" },
      { label: "Réservation entretien d'orientation", date: "Disponible maintenant", statut: "ouvert" },
    ],
    faq: [
      { q: "À quel moment commencer la préparation aux oraux ?", a: "Idéalement dès le début de votre préparation globale — et non après les résultats d'admissibilité. Pour les concours sur titres (sage-femme, puéricultrice, aide-soignant, auxiliaire de puériculture…), l'entretien est l'épreuve unique : la préparation de l'oral EST la préparation du concours." },
      { q: "Combien de simulations sont nécessaires pour progresser ?", a: "En général, 3 à 5 simulations espacées et suivies d'un débriefing approfondi transforment radicalement une prestation. La première simulation est souvent difficile — c'est normal et nécessaire : c'est là que nous identifions précisément ce qu'il faut travailler." },
      { q: "Les simulations sont-elles adaptées à mon concours spécifique ?", a: "Oui. Chaque simulation est calibrée sur votre épreuve : durée officielle, exposé initial (5 ou 10 minutes selon les concours), type de questions. Un jury d'ATSEM ne pose pas les mêmes questions qu'un jury d'ingénieur en chef — nous reproduisons les conditions réelles aussi fidèlement que possible." },
      { q: "La préparation couvre-t-elle les examens professionnels ?", a: "Oui, y compris les entretiens sur dossier (attaché principal, rédacteur principal, classe exceptionnelle des filières sociales…). Le jury ayant lu votre dossier, les questions sont précises et personnelles : nous simulons cet entretien après avoir étudié votre dossier, comme le fera le vrai jury." },
    ],
    sourceOfficielle: "https://www.cdg971.com/fr/concours-examens/calendrier-et-inscription",
  },
};

export const FORMATIONS_LIST = Object.entries(FORMATIONS).map(([slug, f]) => ({
  slug,
  titre: f.titre,
  categorie: f.categorie,
  filiere: f.filiere,
  type: f.type,
  desc: f.descCourte,
  duree: f.duree,
  taux: f.tauxReussite,
  color: f.color,
  accent: f.accent,
}));
